using Microsoft.Extensions.Configuration;

namespace ContosoDashboard.Services;

/// <summary>
/// Local filesystem implementation of IFileStorageService
/// Stores files in AppData/uploads directory structure
/// </summary>
public class LocalFileStorageService : IFileStorageService
{
    private readonly string _basePath;
    private readonly ILogger<LocalFileStorageService> _logger;

    public LocalFileStorageService(IConfiguration configuration, ILogger<LocalFileStorageService> logger)
    {
        _basePath = Path.Combine(Directory.GetCurrentDirectory(), "AppData", "uploads");
        _logger = logger;
        
        // Ensure base directory exists
        if (!Directory.Exists(_basePath))
        {
            Directory.CreateDirectory(_basePath);
        }
    }

    public async Task<string> UploadAsync(Stream fileStream, string fileName, string contentType, string relativePath)
    {
        var fullPath = Path.Combine(_basePath, relativePath);
        var directory = Path.GetDirectoryName(fullPath);

        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        using var outputStream = new FileStream(fullPath, FileMode.Create);
        await fileStream.CopyToAsync(outputStream);

        _logger.LogInformation("File uploaded to {Path}", relativePath);
        return relativePath;
    }

    public Task DeleteAsync(string relativePath)
    {
        var fullPath = Path.Combine(_basePath, relativePath);
        
        if (File.Exists(fullPath))
        {
            File.Delete(fullPath);
            _logger.LogInformation("File deleted: {Path}", relativePath);
        }

        return Task.CompletedTask;
    }

    public async Task<Stream> DownloadAsync(string relativePath)
    {
        var fullPath = Path.Combine(_basePath, relativePath);
        
        if (!File.Exists(fullPath))
        {
            throw new FileNotFoundException("File not found", relativePath);
        }

        var stream = new FileStream(fullPath, FileMode.Open, FileAccess.Read, FileShare.Read);
        return await Task.FromResult<Stream>(stream);
    }

    public Task<string> GetUrlAsync(string relativePath, TimeSpan expiration)
    {
        // For local storage, return a relative path that can be served by a controller
        // The actual URL will be generated by the DocumentController
        return Task.FromResult($"/api/documents/download?path={Uri.EscapeDataString(relativePath)}");
    }

    public Task<long> GetStorageUsedAsync(string basePath)
    {
        var fullPath = Path.Combine(_basePath, basePath);
        
        if (!Directory.Exists(fullPath))
        {
            return Task.FromResult(0L);
        }

        var files = Directory.GetFiles(fullPath, "*", SearchOption.AllDirectories);
        long totalSize = 0;

        foreach (var file in files)
        {
            var fileInfo = new FileInfo(file);
            totalSize += fileInfo.Length;
        }

        return Task.FromResult(totalSize);
    }
}